---
- name: Update and upgrade apt packages
  become: yes
  apt:
    #upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 # update cache oneday

- name: Install CFSSL
  get_url:
    url: https://storage.googleapis.com/kubernetes-the-hard-way/cfssl/1.4.1/linux/cfssl
    dest: /home/dcn/fault-detection/docs/anisble-playbook/kubernetes-the-hard-way/
    mode: a+x

- name: Install CFSSLjson
  get_url:
    url: https://storage.googleapis.com/kubernetes-the-hard-way/cfssl/1.4.1/linux/cfssljson
    dest: /home/dcn/fault-detection/docs/anisble-playbook/kubernetes-the-hard-way/
    mode: a+x

# - name: Add execute permission cfssl
#   file: dest=/home/dcn/fault-detection/docs/anisble-playbook/kubernetes-the-hard-way/cfssl mode=a+x

# - name: Add execute permission cfssljson
#   file: dest=/home/dcn/fault-detection/docs/anisble-playbook/kubernetes-the-hard-way/cfssljson mode=a+x

- name: Move cfssl to local bin
  command: mv cfssl cfssljson /usr/local/bin/
