---
# - name: inital
#   hosts: localhost
#   #become: yes
#   tasks:
#     - include: tasks/tools.yaml
- name: certificate authority
  hosts: localhost
  #become: yes
  tasks:
    - include: tasks/ca.yaml