---
# - name: inital
#   hosts: localhost
#   #become: yes
#   tasks:
#     - include: tasks/tools.yaml
# - name: Generating certificate authority
#   hosts: localhost
#   #become: yes
#   tasks:
#     - include: tasks/ca.yaml

# - name: Generating Kubernetes Configuration
#   hosts: localhost
#   #become: yes
#   tasks:
#     - include: tasks/kube-config.yaml

- name: Generating the Data Encryption Config and Key
  hosts: localhost
  #become: yes
  tasks:
    - include: tasks/data_encryption.yaml

#### should scp approciate files to each host in cluster
# script shoule be written here before next



